### ISSUE TITLE
Tracking Issue: Support for Previously Hand Written Resources

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-yaml#161]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Support for what are currently SDK defined resources such as `kubernetes:apiextensions.k8s.io:CustomResource`. 

Building on #157

**Comment by AaronFriel** [comment]
I think we can close this as tracked by providers:
- https://github.com/pulumi/pulumi-kubernetes/issues/1971
- https://github.com/pulumi/pulumi-docker/issues/132

The exception might be that it may be worth implementing a kludge to support Kubernetes `CustomResource`, as without it there are a good number of things we can't do in YAML.
