### ISSUE TITLE
pulumi new doesn't work with YAML program templates

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-yaml#186]
https://asciinema.org/a/EuT6CrG15fnLZRou9bkW2FJwM

We need to make sure that users get the full `Pulumi.yaml` file.

**Comment by iwahbe** [comment]
Fixed by https://github.com/pulumi/pulumi/commit/bb2c172d5bc6206860c35628cf7175030d8bfa94.
