### ISSUE TITLE
Yaml strictness flags

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-yaml#192]
Can we have support for disabling functionalities in Pulumi YAML using flags? This could work as a style guide to disable patterns a team might not want occurring. I.e variables, references, functions, expressions etc.

**Comment by iwahbe** [comment]
Can you explain the use case better? Pulumi YAML is already very restrictive. 

P.S. everything except top level declarations is an expression. You wouldn't be able to specify resource properties.

**Comment by dixler** [comment]
> Can you explain the use case better? Pulumi YAML is already very restrictive. 
> 
> 
> 
> P.S. everything except top level declarations is an expression. You wouldn't be able to specify resource properties. 

Sure. I want to manage parts of my linux system using Pulumi YAML, it would be nice to be able to strictly control the features of the Pulumi YAML DSL that are enabled.

I want to disable all of the methodCalls/templating/string manip/variables/references and use it similar to a k8s YAML where everything is a literal. Obviously I just don't have to use those features, but I think being able to codify that policy would be helpful. It would force me to acknowledge the levels of complexity in my Pulumi YAML program and whether I want to eject to a language or change a flag.

To make this request less specific to just my use case, I figured we could put flags to toggle different groups of features.

It's a bit of a bold ask for a feature, but I do think YAML is a good language for configuration and these flags would align with encouraging users to eject when their YAML gets more complex. WDYT?

**Comment by AaronFriel** [comment]
Consider this example program:

```yaml
resources:
  myBucket:
    type: aws:s3:Bucket
    properties:
      bucket: foobar-1234 // a unique name for a new bucket
  myHtmlFile:
    type: aws:s3:BucketObject
    properties:
      bucket: foobar-1234
```

Although in theory this program could work, it has a race condition on the bucket being created before the object. Expressions like `${myBucket.bucket}` are not just helpful, they're necessary.

And if expressions are necessary, then we need at least some basic tools to work on them, and so on. Closing this for now, but let's reopen if there's a pressing need, a motivating example, to restrict certain functionality in expressions.
