### ISSUE TITLE
Support stack references with interpolated stack names

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-yaml#198]
When declaring a Stack Reference like below, we error with "the first argument to Fn::StackReference must be a string literal".

```yaml
variables: 
  kubeconfig:
    Fn::StackReference:
      - ${org}/${eksStackProject}/${pulumi.stack}
      - kubeconfig
```

Stack references are represented as resource-like objects and like resources, have a lexical name (not part of our YAML API), a unique name, and arguments that may optionally define a stack referent. From the Go API:

```go
var uniqueName string
var stackReferentName pulumi.String // an Input of string

// if stackReferentName is defined and provided in args below, it must be an Output that returns a orgName/projectFoo/stackBar
// if it is not, then the uniqueName must be a stack referent name

lexicalName, err := pulumi.NewStackReference(ctx, uniqueName, &pulumi.StackReferenceArgs{
  Name = stackReferentName 
})
```

Does changing the unique name of this name cause a "replace" for downstream resources that depend on the name?

* If so, do we need to add a unique name to the StackReference function so that it can serve as that key?
* If not, does the unique name matter and can we generate an arbitrary unique name for codegen?

**Comment by Frassle** [comment]
Why are stack references an Fn:: function in the first place? They're just a built in resource type, why not just declare it like any other resource?

**Comment by AaronFriel** [comment]
Our docs suggest `ctx.NewStackReference()` and friends: https://www.pulumi.com/docs/intro/concepts/stack/#stackreferences

We want to be able to convert stack references into those functions instead of having `pulumi convert` create a resource which doesn't correspond to our docs.

**Comment by AaronFriel** [comment]
Hm, I spoke too soon if that's just a resource constructor. Maybe you're right, and we put them in the resources section as resources.

**Comment by cnunciato** [comment]
Would be awesome to see this land soon! 🙏 Without it, I'm not sure how usable Stack References are going to be in practice. Is there any workaround in the meantime?
