### ISSUE TITLE
Base64 decoding function

### ISSUE THREAD

**Issue by BoSoeborgPetersen** [pulumi/pulumi-yaml#213]
## Hello!
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
I would like to take the KubeConfig from 'azure-native:containerservice:ManagedCluster' and use it to create a kubernetes provider ('pulumi:providers:kubernetes'), using Pulumi Yaml, but for that I need an fn::base64decode function.
Right now I have to split it into two parts, and manually put in the decoded kubeconfig from the first part.

### Affected area/feature
Pulumi Yaml

**Comment by AaronFriel** [comment]
Thanks @BoSoeborgPetersen for reporting this, seems like a blocker for replicating the demos we've done on other clouds on Azure.

@iwahbe a base64 decode intrinsic seems useful, and some providers do force us to manipulate base64 data. Another example of this is the Linode `LkeCluster` which returns a base64 encoded kubeconfig.

**Comment by iwahbe** [comment]
I agree that the extrinsic is useful and worth adding. I recommend the name `Fn::FromBase64`. We want the name to make sense with the existing intrinsic `Fn::ToBase64`.
