### ISSUE TITLE
Health checks for pulumi-language-yaml

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-yaml#242]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Implement https://github.com/pulumi/pulumi/pull/9735 for YAML.

**Comment by Frassle** [comment]
Nope. We treat unimplemented responses as ok, just checking there was a grpc server to respond to us.
