### ISSUE TITLE
Support options on Fn::Invoke such as specifying the provider

### ISSUE THREAD

**Issue by polivbr** [pulumi/pulumi-yaml#246]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

`Fn::Invoke` needs the ability to specify an alternative provider to use for the function invocation, much like the InvokeOptions parameter in the .NET API.

**Comment by AaronFriel** [comment]
@polivbr thanks for creating this!

@iwahbe let's use this issue to track adding options to Invoke.
