### ISSUE TITLE
Update Providers docs with YAML explicit provider config

### ISSUE THREAD

**Issue by aq17** [pulumi/pulumi-yaml#287]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Update[ Providers docs](https://www.pulumi.com/docs/intro/concepts/resources/providers/#explicit-provider-configuration) with YAML example to instantiate an explicit provider, i.ee `pulumi:provider:Foo`

**Comment by mikhailshilkov** [comment]
Please take a look at https://github.com/pulumi/pulumi-hugo/pull/1767

**Comment by aq17** [comment]
> Please take a look at [pulumi/pulumi-hugo#1767](https://github.com/pulumi/pulumi-hugo/pull/1767)

That is very good timing
