### ISSUE TITLE
unexpected configuration type 'bool': valid types are String, List<String>, Number, List<Number>, Boolean, List<Boolean>

### ISSUE THREAD

**Issue by ekini** [pulumi/pulumi-yaml#298]
### What happened?

When trying to use a boolean configuration type the program fails with

```
    error: unexpected configuration type 'bool': valid types are String, List<String>, Number, List<Number>, Boolean, List<Boolean>
    
      on Pulumi.yaml line 6:
       6:     default: true
```
The program is
```yaml
name: pulumitest-static-website
runtime: yaml

configuration:
  test:
    default: true

resources: {}
```

### Steps to reproduce

Create the program as above and try `pulumi up`.

### Expected Behavior

Should see "true" in output.

### Actual Behavior

Error.

### Versions used

CLI          
Version      3.37.1
Go Version   go1.18.4
Go Compiler  gc

Plugins
NAME  VERSION
yaml  unknown

Host     
OS       arch
Version  
Arch     x86_64

This project is written in yaml

pulumi plugin ls | grep yaml
yaml          language  0.5.3    21 MB   14 seconds ago  14 seconds ago

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@aq17 Could you please take a look when you are back next week?

**Comment by aq17** [comment]
> @aq17 Could you please take a look when you are back next week?

@mikhailshilkov 👀
