### ISSUE TITLE
Remove the need for `.append` files in templates

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-yaml#303]
We have a pretty awkward setup for how templates must be authored for YAML - which requires duplication content in `Pulumi.yaml` and `Pulumi.yaml.append`. 

We should move to enabling templates to be authored with just "normal YAML" programs.

**Comment by lukehoban** [comment]
Slight related also https://github.com/pulumi/pulumi/issues/10299.

**Comment by AaronFriel** [comment]
This may be resolved by https://github.com/pulumi/pulumi/pull/10269

**Comment by AaronFriel** [comment]
I've implemented a comment-preserving `pulumi new` command and we can ship this in the next release and remove the `.append` files on our own timeline thereafter: https://github.com/pulumi/pulumi/pull/10401

**Comment by AaronFriel** [comment]
In the next release we will no longer use `.append` files when instantiating templates, and instead use syntax-preserving modifications to the project file.

Tracking removal of .append files here with the milestone set out in the future (M79).
https://github.com/pulumi/templates/issues/325

**Comment by Frassle** [comment]
We had to revert https://github.com/pulumi/pulumi/pull/10401, it was causing timeouts in CI.

**Comment by AaronFriel** [comment]
Merged again. https://github.com/pulumi/pulumi/pull/10437
