### ISSUE TITLE
Accessing sys variables from code brakes the Pulumi build 

### ISSUE THREAD

**Issue by dongqiaoyang** [pulumi/pulumi-yaml#380]
### What happened?

scripts that contains sys variables are interpreted as Pulumi variables and breaks the build.

### Steps to reproduce

Pulumi.yaml

  f1-sp:
    type: google-native:bigquery/v2:Routine
    properties:
      project: ${project}
      routineType: PROCEDURE
      datasetId: dataset_v2_test
      routineReference: 
        datasetId: dataset_v2_test
        project: ${project}
        routineId: sp1
      definitionBody: >
          BEGIN
          select ${sys.now};
          END;
    options:
      dependsOn:
        - ${f1-dataset}

### Expected Behavior

Stored procedure to be created with ${sys.now} within the definition body 

### Actual Behavior

Build failed

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Removed my assignment since the escaping issue is fixed from #382 but will wait on user feedback first before closing this one out

**Comment by AaronFriel** [comment]
@dongqiaoyang it looks like @Zaid-Ajaj fixed this in #382 and per his suggestions above.

If that isn't the case, please reopen this issue or ask us to do so and we'll take a look!
