### ISSUE TITLE
Update examples, templates, docs with `config` key

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-yaml#400]
User-facing materials should reflect the `config` key declared in project config. The Pulumi YAML reference should point to the project file for information on declaring config.

- [x] [pulumi/examples](https://github.com/pulumi/examples)
- [ ] [pulumi/templates](https://github.com/pulumi/templates)
- [ ] [pulumi/docs](https://github.com/pulumi/docs)

**Comment by aq17** [comment]
Going to close this as duplicate as we have individual tickets 

- https://github.com/pulumi/pulumi-yaml/issues/404
- https://github.com/pulumi/examples/issues/1304
- https://github.com/pulumi/templates/issues/453
