### ISSUE TITLE
[Docs] Update YAML reference doc to include properties of builtin pulumi variable

### ISSUE THREAD

**Issue by scottslowe** [pulumi/pulumi-yaml#430]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Per @AaronFriel, there are three properties exposed on the builtin `pulumi` variable: `pulumi.cwd`, `pulumi.project`, and `pulumi.stack`. However, these properties do not seem to be documented in the Pulumi reference documentation.

### Affected area/feature

The Pulumi YAML documentation

**Comment by aq17** [comment]
Closed via https://github.com/pulumi/pulumi-hugo/pull/2344
