### ISSUE TITLE
No support for `organization` builtin

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi-yaml#461]
Trying to use pulumi convert from YAML to generate examples and there is no support for the typescript equivalent:

```ts
const organization = pulumi.getOrganization();
```

Looks like we have support for project and stack builtins but not this one.

**Comment by AaronFriel** [comment]
Related: since [getOrganization is now total in other languages, returning "organization" by default](https://github.com/pulumi/pulumi/pull/10820) we can add this builtin and have it behave identically.
