### ISSUE TITLE
Support `deleteWith` resource option

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-yaml#631]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We should have support for the `deleteWith` resource option in YAML.

**Comment by justinvp** [comment]
Wasn't this added in #437? What's missing?

**Comment by iwahbe** [comment]
Ah, it's `deletedWith`, not `deleteWith`. I just can't read the error messages.
