### ISSUE TITLE
Released version of `pulumi-yaml` on official download page is a dynamically linked binary

### ISSUE THREAD

**Issue by stooj** [pulumi/pulumi-yaml#656]
### What happened?

Version 3.133.0 of pulumi-yaml (downloaded from https://www.pulumi.com/docs/iac/download-install/versions/) is a statically linked binary, so it works on my NixOS installation

```
./v3.133.0/pulumi-language-yaml: ELF 64-bit LSB executable, statically linked
```

Since 3.134.0, all `pulumi-yaml` binaries have been dynamically linked, so I can't run them without recompiling.

```
./v3.134.0/pulumi-language-yaml: ELF 64-bit LSB executable, dynamically linked
```

Later versions are also dynamically linked

### Example

.

### Output of `pulumi about`

Various versions

### Additional context

Thanks!

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment]
This has been fixed with pulumi-yaml 1.11.1, which will be released with the next pulumi release (3.137.0)
